
#include "sdk/sdk.buildv1.1.15/windows_release_mx/include/sdk_engines_2databases_2sqlite_2sqlite.h"

bbInt g_sdk_engines_sqlite_SQLITE_0OK;
bbInt g_sdk_engines_sqlite_SQLITE_0ERROR;
bbInt g_sdk_engines_sqlite_SQLITE_0INTERNAL;
bbInt g_sdk_engines_sqlite_SQLITE_0PERM;
bbInt g_sdk_engines_sqlite_SQLITE_0ABORT;
bbInt g_sdk_engines_sqlite_SQLITE_0BUSY;
bbInt g_sdk_engines_sqlite_SQLITE_0LOCKED;
bbInt g_sdk_engines_sqlite_SQLITE_0NOMEM;
bbInt g_sdk_engines_sqlite_SQLITE_0READONLY;
bbInt g_sdk_engines_sqlite_SQLITE_0INTERRUPT;
bbInt g_sdk_engines_sqlite_SQLITE_0IOERR;
bbInt g_sdk_engines_sqlite_SQLITE_0CORRUPT;
bbInt g_sdk_engines_sqlite_SQLITE_0NOTFOUND;
bbInt g_sdk_engines_sqlite_SQLITE_0FULL;
bbInt g_sdk_engines_sqlite_SQLITE_0CANTOPEN;
bbInt g_sdk_engines_sqlite_SQLITE_0PROTOCOL;
bbInt g_sdk_engines_sqlite_SQLITE_0EMPTY;
bbInt g_sdk_engines_sqlite_SQLITE_0SCHEMA;
bbInt g_sdk_engines_sqlite_SQLITE_0TOOBIG;
bbInt g_sdk_engines_sqlite_SQLITE_0CONSTRAINT;
bbInt g_sdk_engines_sqlite_SQLITE_0MISMATCH;
bbInt g_sdk_engines_sqlite_SQLITE_0MISUSE;
bbInt g_sdk_engines_sqlite_SQLITE_0NOLFS;
bbInt g_sdk_engines_sqlite_SQLITE_0AUTH;
bbInt g_sdk_engines_sqlite_SQLITE_0FORMAT;
bbInt g_sdk_engines_sqlite_SQLITE_0RANGE;
bbInt g_sdk_engines_sqlite_SQLITE_0NOTADB;
bbInt g_sdk_engines_sqlite_SQLITE_0NOTICE;
bbInt g_sdk_engines_sqlite_SQLITE_0WARNING;
bbInt g_sdk_engines_sqlite_SQLITE_0ROW;
bbInt g_sdk_engines_sqlite_SQLITE_0DONE;

void mx2_sdk_engines_2databases_2sqlite_2sqlite_init_f(){
  g_sdk_engines_sqlite_SQLITE_0OK=bbInt(0);
  g_sdk_engines_sqlite_SQLITE_0ERROR=1;
  g_sdk_engines_sqlite_SQLITE_0INTERNAL=2;
  g_sdk_engines_sqlite_SQLITE_0PERM=3;
  g_sdk_engines_sqlite_SQLITE_0ABORT=4;
  g_sdk_engines_sqlite_SQLITE_0BUSY=5;
  g_sdk_engines_sqlite_SQLITE_0LOCKED=6;
  g_sdk_engines_sqlite_SQLITE_0NOMEM=7;
  g_sdk_engines_sqlite_SQLITE_0READONLY=8;
  g_sdk_engines_sqlite_SQLITE_0INTERRUPT=9;
  g_sdk_engines_sqlite_SQLITE_0IOERR=10;
  g_sdk_engines_sqlite_SQLITE_0CORRUPT=11;
  g_sdk_engines_sqlite_SQLITE_0NOTFOUND=12;
  g_sdk_engines_sqlite_SQLITE_0FULL=13;
  g_sdk_engines_sqlite_SQLITE_0CANTOPEN=14;
  g_sdk_engines_sqlite_SQLITE_0PROTOCOL=15;
  g_sdk_engines_sqlite_SQLITE_0EMPTY=16;
  g_sdk_engines_sqlite_SQLITE_0SCHEMA=17;
  g_sdk_engines_sqlite_SQLITE_0TOOBIG=18;
  g_sdk_engines_sqlite_SQLITE_0CONSTRAINT=19;
  g_sdk_engines_sqlite_SQLITE_0MISMATCH=20;
  g_sdk_engines_sqlite_SQLITE_0MISUSE=21;
  g_sdk_engines_sqlite_SQLITE_0NOLFS=22;
  g_sdk_engines_sqlite_SQLITE_0AUTH=23;
  g_sdk_engines_sqlite_SQLITE_0FORMAT=24;
  g_sdk_engines_sqlite_SQLITE_0RANGE=25;
  g_sdk_engines_sqlite_SQLITE_0NOTADB=26;
  g_sdk_engines_sqlite_SQLITE_0NOTICE=27;
  g_sdk_engines_sqlite_SQLITE_0WARNING=28;
  g_sdk_engines_sqlite_SQLITE_0ROW=100;
  g_sdk_engines_sqlite_SQLITE_0DONE=101;
}
