
#ifndef MX2_SDK_ENGINES_2DATABASES_2SQLITE_2SQLITE_H
#define MX2_SDK_ENGINES_2DATABASES_2SQLITE_2SQLITE_H

#include <bbmonkey.h>

extern bbInt g_sdk_engines_sqlite_SQLITE_0OK;
extern bbInt g_sdk_engines_sqlite_SQLITE_0ERROR;
extern bbInt g_sdk_engines_sqlite_SQLITE_0INTERNAL;
extern bbInt g_sdk_engines_sqlite_SQLITE_0PERM;
extern bbInt g_sdk_engines_sqlite_SQLITE_0ABORT;
extern bbInt g_sdk_engines_sqlite_SQLITE_0BUSY;
extern bbInt g_sdk_engines_sqlite_SQLITE_0LOCKED;
extern bbInt g_sdk_engines_sqlite_SQLITE_0NOMEM;
extern bbInt g_sdk_engines_sqlite_SQLITE_0READONLY;
extern bbInt g_sdk_engines_sqlite_SQLITE_0INTERRUPT;
extern bbInt g_sdk_engines_sqlite_SQLITE_0IOERR;
extern bbInt g_sdk_engines_sqlite_SQLITE_0CORRUPT;
extern bbInt g_sdk_engines_sqlite_SQLITE_0NOTFOUND;
extern bbInt g_sdk_engines_sqlite_SQLITE_0FULL;
extern bbInt g_sdk_engines_sqlite_SQLITE_0CANTOPEN;
extern bbInt g_sdk_engines_sqlite_SQLITE_0PROTOCOL;
extern bbInt g_sdk_engines_sqlite_SQLITE_0EMPTY;
extern bbInt g_sdk_engines_sqlite_SQLITE_0SCHEMA;
extern bbInt g_sdk_engines_sqlite_SQLITE_0TOOBIG;
extern bbInt g_sdk_engines_sqlite_SQLITE_0CONSTRAINT;
extern bbInt g_sdk_engines_sqlite_SQLITE_0MISMATCH;
extern bbInt g_sdk_engines_sqlite_SQLITE_0MISUSE;
extern bbInt g_sdk_engines_sqlite_SQLITE_0NOLFS;
extern bbInt g_sdk_engines_sqlite_SQLITE_0AUTH;
extern bbInt g_sdk_engines_sqlite_SQLITE_0FORMAT;
extern bbInt g_sdk_engines_sqlite_SQLITE_0RANGE;
extern bbInt g_sdk_engines_sqlite_SQLITE_0NOTADB;
extern bbInt g_sdk_engines_sqlite_SQLITE_0NOTICE;
extern bbInt g_sdk_engines_sqlite_SQLITE_0WARNING;
extern bbInt g_sdk_engines_sqlite_SQLITE_0ROW;
extern bbInt g_sdk_engines_sqlite_SQLITE_0DONE;

#endif
